### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AnhAnhii** [Desamod/OkxRacerBot#10]
Traceback (most recent call last):
  File "C:\Users\ad\Downloads\BOT Telegram\OkxRacerBot-master\OkxRacerBot-master\venv\lib\site-packages\pydantic_settings\sources.py", line 323, in __call__
    field_value = self.prepare_field_value(field_name, field, field_value, value_is_complex)
  File "C:\Users\ad\Downloads\BOT Telegram\OkxRacerBot-master\OkxRacerBot-master\venv\lib\site-packages\pydantic_settings\sources.py", line 513, in prepare_field_value
    raise e
  File "C:\Users\ad\Downloads\BOT Telegram\OkxRacerBot-master\OkxRacerBot-master\venv\lib\site-packages\pydantic_settings\sources.py", line 510, in prepare_field_value
    value = self.decode_complex_value(field_name, field, value)
  File "C:\Users\ad\Downloads\BOT Telegram\OkxRacerBot-master\OkxRacerBot-master\venv\lib\site-packages\pydantic_settings\sources.py", line 147, in decode_complex_value
    return json.loads(value)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ad\Downloads\BOT Telegram\OkxRacerBot-master\OkxRacerBot-master\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\ad\Downloads\BOT Telegram\OkxRacerBot-master\OkxRacerBot-master\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\ad\Downloads\BOT Telegram\OkxRacerBot-master\OkxRacerBot-master\bot\utils\launcher.py", line 11, in <module>
    from bot.config import settings
  File "C:\Users\ad\Downloads\BOT Telegram\OkxRacerBot-master\OkxRacerBot-master\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "C:\Users\ad\Downloads\BOT Telegram\OkxRacerBot-master\OkxRacerBot-master\bot\config\config.py", line 26, in <module>
    settings = Settings()
  File "C:\Users\ad\Downloads\BOT Telegram\OkxRacerBot-master\OkxRacerBot-master\venv\lib\site-packages\pydantic_settings\main.py", line 85, in __init__
    **__pydantic_self__._settings_build_values(
  File "C:\Users\ad\Downloads\BOT Telegram\OkxRacerBot-master\OkxRacerBot-master\venv\lib\site-packages\pydantic_settings\main.py", line 187, in _settings_build_values
    return deep_update(*reversed([source() for source in sources]))
  File "C:\Users\ad\Downloads\BOT Telegram\OkxRacerBot-master\OkxRacerBot-master\venv\lib\site-packages\pydantic_settings\main.py", line 187, in <listcomp>
    return deep_update(*reversed([source() for source in sources]))
  File "C:\Users\ad\Downloads\BOT Telegram\OkxRacerBot-master\OkxRacerBot-master\venv\lib\site-packages\pydantic_settings\sources.py", line 685, in __call__
    data: dict[str, Any] = super().__call__()
  File "C:\Users\ad\Downloads\BOT Telegram\OkxRacerBot-master\OkxRacerBot-master\venv\lib\site-packages\pydantic_settings\sources.py", line 325, in __call__
    raise SettingsError(
pydantic_settings.sources.SettingsError: error parsing value for field "BOOSTERS" from source "DotEnvSettingsSource"

**Comment by Desamod** [comment]
Show me your .env file

**Comment by wannaD1E** [comment]
BOOSTERS у тебя TRUE стоит, сотри вообще.
