### ISSUE TITLE
I have this error when i try to start bot with run.bat. I've edited ,env file as instruction says so i don't know where this error comes from

### ISSUE THREAD

**Issue by Victorious-man** [Desamod/OkxRacerBot#5]
(venv) D:\System\Desktop\Scripts\OkxRacerBot>run.bat
Activating virtual environment...
Dependencies already installed, skipping installation.
Skipping .env copying
Starting the bot...
Traceback (most recent call last):
  File "D:\System\Desktop\Scripts\OkxRacerBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "D:\System\Desktop\Scripts\OkxRacerBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "D:\System\Desktop\Scripts\OkxRacerBot\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "D:\System\Desktop\Scripts\OkxRacerBot\bot\core\tapper.py", line 6, in <module>
    from aiocfscrape import CloudflareScraper
  File "D:\System\Desktop\Scripts\OkxRacerBot\venv\Lib\site-packages\aiocfscrape\__init__.py", line 8, in <module>
    import js2py
  File "D:\System\Desktop\Scripts\OkxRacerBot\venv\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "D:\System\Desktop\Scripts\OkxRacerBot\venv\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "D:\System\Desktop\Scripts\OkxRacerBot\venv\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\System\Desktop\Scripts\OkxRacerBot\venv\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "D:\System\Desktop\Scripts\OkxRacerBot\venv\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\System\Desktop\Scripts\OkxRacerBot\venv\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3
done
PLEASE EDIT .ENV FILE

**Comment by Desamod** [comment]
Python version?

**Comment by AKa0258** [comment]
same error here idk why
