### ISSUE TITLE
 error parsing value for field "BOOSTERS" from source "DotEnvSettingsSource" done

### ISSUE THREAD

**Issue by Xamius** [Desamod/OkxRacerBot#7]
Help me understand the error.

> `Traceback (most recent call last):
  File "D:\hamster2\OkxRacerBot1\venv\Lib\site-packages\pydantic_settings\sources.py", line 323, in __call__
    field_value = self.prepare_field_value(field_name, field, field_value, value_is_complex)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\hamster2\OkxRacerBot1\venv\Lib\site-packages\pydantic_settings\sources.py", line 513, in prepare_field_value
    raise e
  File "D:\hamster2\OkxRacerBot1\venv\Lib\site-packages\pydantic_settings\sources.py", line 510, in prepare_field_value
    value = self.decode_complex_value(field_name, field, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\hamster2\OkxRacerBot1\venv\Lib\site-packages\pydantic_settings\sources.py", line 147, in decode_complex_value
    return json.loads(value)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\XamPC\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XamPC\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XamPC\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "D:\hamster2\OkxRacerBot1\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "D:\hamster2\OkxRacerBot1\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "D:\hamster2\OkxRacerBot1\bot\utils\launcher.py", line 10, in <module>
    from bot.config import settings
  File "D:\hamster2\OkxRacerBot1\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "D:\hamster2\OkxRacerBot1\bot\config\config.py", line 25, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "D:\hamster2\OkxRacerBot1\venv\Lib\site-packages\pydantic_settings\main.py", line 85, in __init__
    **__pydantic_self__._settings_build_values(
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\hamster2\OkxRacerBot1\venv\Lib\site-packages\pydantic_settings\main.py", line 187, in _settings_build_values
    return deep_update(*reversed([source() for source in sources]))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\hamster2\OkxRacerBot1\venv\Lib\site-packages\pydantic_settings\main.py", line 187, in <listcomp>
    return deep_update(*reversed([source() for source in sources]))
                                  ^^^^^^^^
  File "D:\hamster2\OkxRacerBot1\venv\Lib\site-packages\pydantic_settings\sources.py", line 685, in __call__
    data: dict[str, Any] = super().__call__()
                           ^^^^^^^^^^^^^^^^^^
  File "D:\hamster2\OkxRacerBot1\venv\Lib\site-packages\pydantic_settings\sources.py", line 325, in __call__
    raise SettingsError(
pydantic_settings.sources.SettingsError: error parsing value for field "BOOSTERS" from source "DotEnvSettingsSource"
done`

**Comment by Xamius** [comment]
You shouldn'T have changed .env
